### PR TITLE
Remove GooFit code from GooTorial repo

### PR DESCRIPTION
**Pull request by cdeil**
I think it's better not to duplicate the GooFit code ... the corresponding code in the GooFit repo has already diverged.

### CODE REVIEW

**Comment by RolfAndreassen** [comment]
It's nice not to duplicate code, true; but it's also nice to have a frozen tutorial that's been tested, doesn't need instructions of the form "Now go install this other repo so you can compile the example code against it", and generally speaking is all of a piece. Having the old code separately saves us from needing to check whether a change to GooFit breaks the tutorial.

**Comment by cdeil** [comment]
I'm hoping at soon there'll be a GooFit package and tutorial that works on my Macbook (see issue https://github.com/GooFit/GooFit/pull/4), though, and this is not very likely to happen if the tutorial uses a  `release_16Jan2013` folder with the old `GooFit` code.

If you want to declare a stable version, create a `GooFit version 0.1` tag:
http://learn.github.com/p/tagging.html

Github will let your users easily download zip files or tarballs (or git clone) the versions of GooFit corresponding to that tag, see e.g.:
https://github.com/astropy/astropy/tags

**Comment by cdeil** [comment]
Now that GooFit works ( see https://github.com/GooFit/GooFit/pull/4 ) I wanted to try out the GooTorial, but the Makefiles currently don't work and I couldn't make them work in 15 min.

The problem I ran into with this solution is that the GooTorial Makefile includes a modified version of the GooFit Makefile, and using the non-modified version doesn't work.

I still think that duplicating GooFit is bad (basically creates a lot of maintenance work for GooTorial to change with GooFit as new bugfixes / features are introduced) and that a solution where the GooTorial Makefile references an existing GooFit build or installation via a shell environment variable would be much better.

**Comment by RolfAndreassen** [comment]
You've convinced me. I'll make a stable tag for the main GooFit repo and then get this to reference it. Probably not today, however.

**Pull request closed without merging**
